### ISSUE TITLE
Pointer on struct is not nil

### ISSUE THREAD

**Issue by thomersch** [facebookgo/ensure#2]
For this simple case, we can trigger a side effect of checking for nil:

    func TestFoo(t *testing.T) {
        var f *struct{}
        ensure.Nil(t, f)
    }

Which will result in:

    --- FAIL: TestFoo (0.00s)
        nil_checking_test.go:12: expected nil value but got: (*struct {})(<nil>)

In the `Nil` function some reflection on the value would be needed. For reference, there is a thread on the golang-nuts mailing list: https://groups.google.com/forum/#!topic/golang-nuts/wnH302gBa4I/discussion

**Comment by daaku** [comment]
This is very much by design -- we wanted the `Nil` check to work as expected for checking for nil a `error`, by far the largest use case. We handle the case you described by doing something like `ensure.True(t, f == nil)`.
